### ISSUE TITLE
`read_csv` from S3 on remote Ray cluster downloads data locally

### ISSUE THREAD

**Issue by matthewdeng** [modin-project/modin#3222]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: maxOS Big Sur 11.2.3
- **Modin version** (`modin.__version__`): 0.10.0
- **Python version**: Python 3.7.10
- **Code we can use to reproduce**:

```python
import ray
import modin.pandas as pd
import time

S3_PATH = "s3://<bucket>/HIGGS.csv"

ray.client().connect()

colnames = ["label"] + ["feature-%02d" % i for i in range(1, 29)]
pd.read_csv(S3_PATH, names=colnames)
```

### Describe the problem

When reading a CSV from S3, Modin will load the entire dataset on the local driver. This leads to slow performance due to being limited by local bandwidth during download, as well as during transfer of the dataset from local to the remote cluster with `ray.put`. 

@wuisawesome mentioned that Modin may be doing this to read the header row from the driver. In the example provided, the column names are being passed into the `names` parameter so this should not be necessary, but as a more generic solution perhaps the dataset could be read solely on the cluster and the header row alone could be passed to the driver if needed.

### Source code / logs

1. Setup Ray Cluster with `ray up modin-xgboost.yaml`
```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: modin-xgboost

min_workers: 0
max_workers: 3

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2

auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/matt-test.pem

docker:
     image: rayproject/ray:nightly
     container_name: ray_container

available_node_types:
    ray.head.default:
        min_workers: 0
        max_workers: 0
        node_config:
            KeyName: matt-test
            InstanceType: m5.4xlarge
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 100
    ray.worker.default:
        min_workers: 0
        max_workers: 3
        node_config:
            KeyName: matt-test
            InstanceType: m5.4xlarge

head_node_type: ray.head.default

setup_commands:
  - pip install -U git+https://github.com/ray-project/xgboost_ray.git#xgboost_ray
  - pip install -U modin s3fs boto3 botocore aiobotocore
 ```
2. Set up port forwarding: `ray attach modin-xgboost.yaml -p 10001`
3. Update `distributed_read_csv.py` python script with time logging:
```python
import ray
import modin.pandas as pd
import time

S3_PATH = "s3://<bucket>/HIGGS.csv"

ray.client().connect()

start = time.time()
print(f"start time: {start}")

colnames = ["label"] + ["feature-%02d" % i for i in range(1, 29)]
pd.read_csv(S3_PATH, names=colnames)

end = time.time()
total = end - start

print(f"end time: {end}")
print(f"time taken: {total}")
```
4. Run script and observe that it takes 27 minutes:
```bash
(python37) ~/workspace/scratch/modin RAY_ADDRESS="localhost:10001" python distributed_read_csv.py
start time: 1625676042.23508
end time: 1625677661.523253
time taken: 1619.2881729602814
```
5. Traceback from `py-spy`:
```bash
(python37) ~/workspace/scratch/modin sudo py-spy dump --pid 89490
Process 89490: python distributed_read_csv.py
Python v3.7.10 (/Users/matt/anaconda3/envs/python37/bin/python3.7)

Thread 0x10DE63E00 (idle): "MainThread"
    wait (threading.py:300)
    wait (threading.py:552)
    sync (fsspec/asyn.py:58)
    _fetch_range (s3fs/core.py:2047)
    _fetch_range (s3fs/core.py:1904)
    _fetch (fsspec/caching.py:390)
    read (fsspec/spec.py:1469)
    offset (modin/engines/base/io/text/text_file_dispatcher.py:169)
    partitioned_file (modin/engines/base/io/text/text_file_dispatcher.py:263)
    _read (modin/engines/base/io/text/csv_dispatcher.py:153)
    read (modin/engines/base/io/file_dispatcher.py:67)
    _read_csv (modin/data_management/factories/factories.py:206)
    read_csv (modin/data_management/factories/dispatcher.py:172)
    _read (modin/pandas/io.py:59)
    read_csv (modin/pandas/io.py:133)
    <module> (distributed_read_csv.py:14)
Thread 0x70000091B000 (idle): "Thread-1"
    _poll_connectivity (grpc/_channel.py:1369)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x700000EA1000 (idle): "Thread-6"
    wait (threading.py:300)
    _wait_once (grpc/_common.py:106)
    wait (grpc/_common.py:141)
    _next (grpc/_channel.py:794)
    __next__ (grpc/_channel.py:416)
    _data_main (ray/util/client/dataclient.py:69)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000013A4000 (idle): "Thread-7"
    wait (threading.py:300)
    _wait_once (grpc/_common.py:106)
    wait (grpc/_common.py:141)
    _next (grpc/_channel.py:794)
    __next__ (grpc/_channel.py:416)
    _log_main (ray/util/client/logsclient.py:42)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000018A7000 (idle): "Thread-8"
    channel_spin (grpc/_channel.py:1235)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x700001DAA000 (idle): "Thread-9"
    wait (threading.py:296)
    get (queue.py:170)
    consume_request_iterator (grpc/_channel.py:195)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000022AD000 (idle): "Thread-10"
    wait (threading.py:296)
    get (queue.py:170)
    consume_request_iterator (grpc/_channel.py:195)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000027B0000 (idle): "fsspecIO"
    select (selectors.py:558)
    _run_once (asyncio/base_events.py:1750)
    run_forever (asyncio/base_events.py:541)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x700002DB9000 (idle): "ThreadPoolExecutor-0_0"
    _worker (concurrent/futures/thread.py:78)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000032BC000 (idle): "ThreadPoolExecutor-0_1"
    _worker (concurrent/futures/thread.py:78)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000037BF000 (idle): "ThreadPoolExecutor-0_2"
    _worker (concurrent/futures/thread.py:78)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x700003CC2000 (idle): "ThreadPoolExecutor-0_3"
    _worker (concurrent/futures/thread.py:78)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000041C5000 (idle): "ThreadPoolExecutor-0_4"
    _worker (concurrent/futures/thread.py:78)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x7000046C8000 (idle): "ThreadPoolExecutor-0_5"
    _worker (concurrent/futures/thread.py:78)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
Thread 0x700004BCB000 (idle): "ThreadPoolExecutor-0_6"
    _worker (concurrent/futures/thread.py:78)
    run (threading.py:870)
    _bootstrap_inner (threading.py:926)
    _bootstrap (threading.py:890)
```

6. Changing `pd.read_csv(S3_PATH, names=colnames)` to `ray.get(ray.remote(pd.read_csv).remote(S3_PATH, names=colnames))` reduces the time from 27 minutes to 4 minutes:
```bash
(python37) ~/workspace/scratch/modin RAY_ADDRESS="localhost:10001" python distributed_read_csv.py
start time: 1625678573.241013
end time: 1625678818.697503
time taken: 245.45649003982544
```
